name: "multievent pipeline"
on: 
  push:
    branches:
      - master
      - test
  pull_request: 
    branches:
      - master

  workflow_dispatch: 

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest 
    steps:
      - name: "running on push"
        run: echo "running on push"

  on-pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "running on pull_request"
        run: echo "running on pr tt"
