name: "multievent pipeline"
on: 
  push:
    branches:
      - master
      - test
  pull_request: 
    branches:
      - master
    types: 
      - opened
      - closed

  workflow_dispatch : 

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest 
    steps:
      - name: "running on push"
        run: echo "running on push"

  on-pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "running on pull_request"
        run: echo "running on pr tt."

  on-pull_request_opened:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: "running on pull_request opened"
        run: echo "running on pull_request opened"

  on-pull_request_closed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: "running on pull_request closed"
        run: echo "running on pull_request closed"

  on-workflow_dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "running on workflow_dispatch"
        run: echo "running on workflow_dispatch  "
  
  