name: "print workflow"
on:
  push:
    branches:
      - master

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: print hello world
        run: echo "hello world"
